version: "3.7"

services:
  guac-server:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guac.rule=Host(`console.${DOMAIN}`)"
      - "traefik.http.routers.guac.entrypoints=websecure"
      - "traefik.http.routers.guac.tls=true"
      - "traefik.http.middlewares.redirect-guac.addPrefix.prefix=/guacamole"
      - "traefik.http.routers.guac.middlewares=redirect-guac"
      - "traefik.http.services.guac-server.loadbalancer.server.port=8080"
  traefik:
    image: traefik:v2.4
    ports:
      - 80:80
      - 443:443
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--log.level=DEBUG"
        # define healthcheck
      - "--ping.entryPoint=ping"
      - "--entryPoints.ping.address=:8082"
        # security & provider config
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
        # define routers for http and https
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
        # define permanent redirect to https
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    networks:
      - srv
