version: "2.2"
services:
  web_0:
    build: ./c2-docker
    tty: true
    restart: always
    entrypoint: /bin/bash
    networks:
      bridge_net:
        ipv4_address: 10.10.10.32
  web:
    build: ./lab-docker
    restart: always
    cap_add:
      - SYS_ADMIN # for SystemD
      - NET_ADMIN # for iptables
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro #needed for systemD. readonly
    networks:
      - bridge_net
      - host_net
    tmpfs:
      - /run
      - /run/lock
networks:
  bridge_net:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1
          ip_range: 10.10.10.32/27
  host_net:
    driver: bridge
