version: "2.1"
services:
  web0:
    build: ./c2-base
    tty: true
    restart: always
    ports:
      - "2222:22"
    networks:
      - web
    volumes:
      - ./c2-base/pssh_hostfile.txt:/root/pssh_hostfile.txt
  web:
    build: ./web-base
    restart: always
    cap_add:
      - SYS_ADMIN # for SystemD
      - NET_ADMIN # for iptables
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro #needed for systemD. readonly
    tmpfs:
      - /run
      - /run/lock
    networks:
      - web
  file-server:
    build: ./file-server
    hostname: file-server
    volumes:
      - ./file-server/files/:/usr/share/nginx/html
    networks:
      - web
networks:
  web:
  srv:
