version: "3.7"

services:
  guacd:
    image: guacamole/guacd
    networks:
      - srv
      - web
  guac-server:
    image: guacamole/guacamole
    ports:
      - "8080:8080"
    depends_on:
      - "guacd"
    environment:
      - GUACD_HOSTNAME=guacd
      - GUACAMOLE_HOME=/etc/guacamole
    networks:
      - srv
    volumes:
      - ./guacamole/user-mapping.xml:/etc/guacamole/user-mapping.xml
volumes:
    pgdata:
