version: "2"
services:
  web1.umcstlab.net:
    build: ./c2-docker
    tty: true
    restart: always
    entrypoint: /bin/bash
    networks:
      bridge_net:
        ipv4_address: 192.168.10.20
  web2.umcstlab.net:
    build: ./lab-docker
    restart: always
    cap_add:
      - SYS_ADMIN # for SystemD
      - NET_ADMIN # for iptables
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:ro #needed for systemD. readonly
    networks:
      - bridge_net
      - host_net
    tmpfs:
      - /run
      - /run/lock
networks:
  bridge_net:
    driver: macvlan
    driver_opts:
      parent: enp58s0f1
    ipam:
      config:
        - subnet: 192.168.10.0/24
          ip_range: 192.168.10.32/28
  host_net:
    driver: bridge
