version: "3.7"

services:
    guacd:
        image: guacamole/guacd
        networks:
          - bridge_net
          - guac_net
    guac-server:
        image: guacamole/guacamole
        ports:
          - "80:8080"
        depends_on:
          - "guacd"
          - "postgres"
        env_file:
          - guac.env
        networks:
          - guac_net
    postgres:
        image: postgres:latest
        volumes:
          - pgdata:/var/lib/postgresql/data
          - ./initdb/initdb.sql:/docker-entrypoint-initdb.d/init-guac.sql
          - ./initdb/addguac.sql:/docker-entrypoint-initdb.d/adduser.sql
        env_file:
          - pgsql.env
        environment:
          - PGDATA=/var/lib/postgresql/data/pgdata
        networks:
          - guac_net
volumes:
    pgdata:
networks:
    bridge_net:
      external: true
    guac_net:
